apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fintech-prod

resources:
  - ../../base/transaction-service.yaml
  - ../../base/policy-service.yaml
  - namespace.yaml
  - ingress.yaml

images:
  - name: transaction-service
    newName: ACCOUNT_ID.dkr.ecr.af-south-1.amazonaws.com/transaction-service
    newTag:  latest
  - name: policy-service
    newName: ACCOUNT_ID.dkr.ecr.af-south-1.amazonaws.com/policy-service
    newTag:  latest

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: transaction-service
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: policy-service

commonLabels:
  environment: prod
  managed-by:  argocd

commonAnnotations:
  deployment.kubernetes.io/managed-by: argocd
